### ISSUE TITLE
Committing different translations to the same pull request, name problem

### ISSUE THREAD

**Issue by aiyodev** [javascript-tutorial/bs.javascript.info#3]
@iliakan Sorry for tagging all the time, can I get your social media where I can contact you with some questions, or just ask them here?

I sent a pull request for the first chapter, and then I did another translation of the second one, and it automatically committed to the already existing pull request, but the name is Introduction to JavaScript, but 2 different chapters are on that pull request, is this a problem? Like do I have to wait until you approve then send another pull request with another commit to master, I'm a bit confused, sorry again for spam tagging.

**Comment by iliakan** [comment]
No problem.

I don't review PRs for translations. How could I do that? I'm not speaking Bosnian.

So you can just commit/merge.

**Comment by aiyodev** [comment]
I don't have the permission to commit to the repo, it doesn't allow me

**Comment by aiyodev** [comment]
@iliakan I can't push my own pull request, and I don't have push access to the repo obviously so someone else has to merge

**Comment by iliakan** [comment]
You got the email, the invitation to the team.
