### ISSUE TITLE
I am in the maintainer list but dont have push access

### ISSUE THREAD

**Issue by aiyodev** [javascript-tutorial/bs.javascript.info#4]
@iliakan Can you fix this, I don't have anything to do, I want to translate some more chapters today as well

Sorry for the tag again, but you don't seem to respond when I don't tag you

**Comment by iliakan** [comment]
There's the invitation for you.

![image](https://user-images.githubusercontent.com/349336/88294435-e3955780-cd04-11ea-81e2-9652447f6857.png)

Please check your email. You need to accept it to get access.

**Comment by iliakan** [comment]
It's from github.

**Comment by aiyodev** [comment]
Sorry didn't check this email, accepted it, it's working now, thanks

**Comment by aiyodev** [comment]
@iliakan I pushed to the main Bosnian repo, can you just check if that is fine how I did it so I don't mistakenly finish other translations but they're put in the wrong place or something else

**Comment by iliakan** [comment]
Looks ok.
